### ISSUE TITLE
Graylog 2.2.3+7adc951

### ISSUE THREAD

**Issue by connylindquist** [Hobadee/Graylog_ContentPack_pfSense#2]
I cant seem to import this to Graylog. It simply say. 

![image](https://cloud.githubusercontent.com/assets/27331939/26235004/b5aad5b4-3c68-11e7-89d4-0540cb818716.png)

I cant seem to find the error itself though in the logs. (Probably me not knowing how to use the Graylog properly).

**Comment by webmastir** [comment]
Don't import this as a content pack.

See my post [here](https://github.com/noktork/Graylog-CISCO-ASA-Extractor/issues/2#issuecomment-301488945) on another Github pfSense Extractors page.

**Comment by connylindquist** [comment]
Ah, thank you. That worked like a charm. :)
